apiVersion: v1
kind: ConfigMap
metadata:
  name: region000001-cooperate-region-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "catalogService": {
        "getCatalogName": "/catalog/name",
        "getForNs": "/catalog/?ns="
      },
      "pxrBlockProxyService": {
        "postRoot": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?block=$pxr-root-block&path="
      },
      "notificationService": {
        "getNotification": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000783&path=%2Fnotification%2F%3Fis_send%3Dfalse%26is_unread%3Dtrue%26is_approval%3Dfalse%26type%3D0%26num%3D0",
        "putNotification": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000783&path=%2Fnotification%2F"
      },
      "bookOperateService": {
        "postUser": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000783&path=%2Fbook-operate%2Fuser"
      },
      "identityVerificateService": {
        "postUserSettings": "/identity-verificate/user/settings",
        "putVerifyOthers": "/identity-verificate/verify/others/"
      },
      "session": {
        "loginId": "region000001_batch",
        "auth": {
          "member": {
            "add": true
          },
          "app-wf-user": {
              "create": true
          }
        },
        "block": {
          "_value": 1000783,
          "_ver": 3
        },
        "actor": {
          "_value": 1000786,
          "_ver": 3
        }
      },
      "catalog": {
        "globalSettingNs": "catalog/ext/{extName}/setting/global"
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/region000001/cooperate-region-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }