apiVersion: v1
kind: ConfigMap
metadata:
  name: region000001-region-end-of-use-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "catalogService": {
        "getCatalogName": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2Fname",
        "getCatalog": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=$pxr-root-block&path=%2Fcatalog%2F{code}",
        "getForNs": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fcatalog%2F%3Fns%3D"
      },
      "bookOperateService": {
          "postUserDelete": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000783&path=%2Fbook-operate%2Fuser%2Fdelete%3FphysicalDelete%3D{physicalDelete}"
      },
      "bookManageService": {
        "postGetMcdOutput": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%3Foffset%3D{offset}%26limit%3D10",
        "putUpdateMcdOutput": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%2F{id}",
        "postMcbSearch": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fsearch",
        "postGetMcdDataFile": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%2Fcondition%2Fdata_mng%2Fsearch",
        "postCooperateReleaseId": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fcooperate%2Frelease"
      },
      "identityVerificateService": {
        "postCodeVerified": "http://region000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fidentity-verificate%2Fcode%2Fverified"
      },
      "session": {
        "loginId": "region000001_batch",
        "auth": {
            "member": {
                "delete": true
            },
            "book": {
                "create": true
            }
        },
        "block": {
          "_value": 1000783,
          "_ver": 3
        },
        "actor": {
          "_value": 1000786,
          "_ver": 3
        }
      },
      "catalog": {
        "globalSettingNs": "catalog/ext/{extName}/setting/global",
        "regionTouNs": "catalog/ext/{extName}/terms-of-use/region/actor_{actor}"
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/region000001/region-end-of-use-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }