apiVersion: v1
kind: ConfigMap
metadata:
  name: application000001-delete-user-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "catalogService": {
        "getCatalogName": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=$pxr-root-block&path=%2Fcatalog%2Fname",
        "getCatalog": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=$pxr-root-block&path=%2Fcatalog%2F{code}",
        "getForNs": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=$pxr-root-block&path=%2Fcatalog%2F%3Fns%3D"
      },
      "bookManageService": {
        "postGetMcdOutputCodeDataFile": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%2Fcondition%2Fdata_mng%2Fsearch%3Foffset%3D{offset}%26limit%3D10%26approved%3D{approved}",
        "postUpdateMcdOutputCodeDataFile": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%2Fcondition%2Fdata_mng%2F{id}",
        "postMcbSearch": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=$pxr-root-block&path=%2Fbook-manage%2Fsearch%3FdisableFlg%3D1"
      },
      "bookOperateService": {
        "postUserList": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000407&path=%2Fbook-operate%2Fuser%2Flist",
        "deleteUserData": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fbook-operate&block=1000407&path=%2Fbook-operate%2Fstore%2F{userId}%3FphysicalDelete%3D{physicalDelete}"
      },
      "session": {
        "loginId": "application000001_batch",
        "auth": {
            "book": {
                "create": true
            }
        },
        "block": {
          "_value": 1000407,
          "_ver": 1
        },
        "actor": {
          "_value": 1000436,
          "_ver": 1
        }
      },
      "catalog": {
        "globalSettingNs": "catalog/ext/{extName}/setting/global",
        "pxrRootBlockNs": "catalog/ext/{extName}/block/pxr-root",
        "platformTouNs": "catalog/ext/{extName}/terms-of-use/platform",
        "regionTouNs": "catalog/ext/{extName}/terms-of-use/region/actor_{actor}"
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/application000001/delete-user-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }