apiVersion: v1
kind: ConfigMap
metadata:
  name: application000001-link-ctoken-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "localCTokenService": {
        "postLedger": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Flocal-ctoken&block=1000407&path=%2Flocal-ctoken%2Fledger",
        "getLedgerCount": "http://application000001-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Flocal-ctoken&block=1000407&path=%2Flocal-ctoken%2Fledger%2Fcount"
      },
      "session": {
        "loginId": "application000001_batch",
        "block": {
          "_value": 1000407,
          "_ver": 1
        },
        "actor": {
          "_value": 1000436,
          "_ver": 1
        }
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/application000001/link-ctoken-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }