apiVersion: v1
kind: ConfigMap
metadata:
  name: root-book-end-of-use-batch-container-config-map
  namespace: pxross1
data:
  config.json: |
    {
      "bookManageService": {
        "getPlatformDeletionTarget": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fterm_of_use%2Fplatform%2Fdeletion%2Ftarget%3Foffset%3D{offset}%26limit%3D10",
        "forceDeletion": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fforce-deletion",
        "forceEnable": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Fforce-enable",
        "postGetOutputCode": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%3Foffset%3D{offset}%26limit%3D10",
        "postOutputPrepare": "http://root-service/pxr-block-proxy/pxr-block-proxy/?from_path=%2Fpxr-book-manage&block=$pxr-root-block&path=%2Fbook-manage%2Foutput%2Fcondition%2Fprepare"
      },
      "session": {
        "loginId": "root_batch",
        "auth": {
          "member": {
            "add": true,
            "update": true
          },
          "book": {
            "create": true
          }
        },
        "block": {
          "_value": 1000401,
          "_ver": 1
        },
        "actor": {
          "_value": 1000431,
          "_ver": 1
        }
      },
      "timezone": "Asia/Tokyo"
    }
  log4js.config.json: |
    {
      "appenders": {
        "ConsoleLogAppender": {
          "type": "console"
        },
        "ApplicationLogAppender": {
          "type": "dateFile",
          "filename": "./efs/root/book-end-of-use-batch/application.log",
          "pattern": ".yyyy-MM-dd",
          "numBackups": 30,
          "alwaysIncludePattern": false,
          "layout": {
            "type": "pattern",
            "pattern": "[%d{yyyy-MM-dd hh:mm:ss.SSS}] [%p] %m"
          }
        }
      },
      "replaceConsole": true,
      "categories": {
        "default": {
          "appenders": [
            "ConsoleLogAppender"
          ],
          "level": "all"
        },
        "application": {
          "appenders": [
            "ApplicationLogAppender"
          ],
          "level": "all"
        }
      }
    }